"""
Blood Bank Decision Support System — Synthetic Operational Data Generator
===========================================================================

WHAT THIS SCRIPT DOES
----------------------
Builds the unit-level operational layer (blood_units, blood_requests,
blood_issues) and the enriched donor layer (donors_final, compatibility_rules)
on top of two REAL, UNMODIFIED source datasets:

    - donors.csv            (real: one branch's donor registry)
    - donation_history.csv  (real: that branch's donation events)

and uses two REAL, UNMODIFIED macro time series only as a SHAPE reference
(never as a row-level source of truth for this branch):

    - supply_data.csv    (real: national/regional daily collection totals)
    - demand_data.csv    (real: national/regional daily demand totals)

KEY DESIGN DECISION (see analysis report)
------------------------------------------
donors.csv/donation_history.csv operate at ~1/150-200th the scale of
supply_data.csv/demand_data.csv. They are NOT the same physical system at
different granularity - they are a single branch's real donor roster vs.
a real national/regional reporting feed. Therefore:

  - blood_units.csv is generated by exploding the REAL donation_history.csv
    1:1 (every real donation becomes 1 or 2 real blood units, per its own
    units_donated value). No unit is invented independently of a real
    donation record.

  - blood_requests.csv total volume is anchored to this branch's own real
    supply (sum of blood_units), scaled by the REAL national demand/supply
    utilization ratio per blood group (so a structurally tight group like
    AB nationally stays tight at branch level too). Its day-to-day SHAPE
    (trend, seasonality, the 2020 dip) is copied from the REAL demand_data.csv
    daily pattern, only ever used as a proportional weight, never as an
    absolute row-level number for this branch.

  - blood_issues.csv is produced by actually simulating FEFO
    (first-expiry-first-out) allocation of available compatible units
    against priority-ordered requests. Shortages are a real emergent
    property of the simulation, not injected.

REPRODUCIBILITY
----------------
All randomness is derived from a single seed via numpy's Generator with
Philox bit generator + per-purpose sub-streams (donor Rh assignment,
request sizing, priority draws, quality-hold draws) so re-running this
script with the same seed and the same source files always produces
byte-identical output.

CLINICAL DISCLAIMER
---------------------
Rh distribution, RBC shelf-life, ABO/Rh compatibility, and priority
classification below are DOCUMENTED, TEXTBOOK / PUBLISHED-LITERATURE
assumptions used to make the synthetic data internally plausible. None
of this is a substitute for review and sign-off by a licensed blood-bank
professional before any real clinical or operational use.
"""

import numpy as np
import pandas as pd
from pathlib import Path

# ----------------------------------------------------------------------------
# CONFIG (all "rule/config" constants live here, nowhere else, on purpose)
# ----------------------------------------------------------------------------
SEED = 42
# Paths are resolved relative to this script's own location, so the package
# is portable (works from any repo checkout, not just this sandbox).
BASE = Path(__file__).resolve().parent.parent
REAL = BASE / "data" / "real"
OUT_SYN = BASE / "data" / "synthetic"
OUT_RULES = BASE / "data" / "rules"
DONOR_SOURCE_DIR = BASE / "data" / "source"  # original donors.csv / donation_history.csv

RH_POSITIVE_PROB = 0.94
# Source: Patidar et al. 2021, "Distribution of ABO and Rh(D) blood groups
# in India: A systematic review" (ISBT Science Series) - pooled analysis of
# ~1.43M Indian donors found Rh(D)-positive 94.13%, Rh(D)-negative 5.87%.
# Several independent regional Indian donor studies (Karnataka, Maharashtra,
# Uttarakhand) converge on 91-96% Rh+. Applied UNIFORMLY across ABO groups
# here as a simplifying assumption - real per-ABO Rh skew exists in the
# literature but is small and inconsistent across studies. MUST be replaced
# with this specific branch's own donor registry statistics before production.

SHELF_LIFE_DAYS = 42
# Standard CPDA-1 anticoagulant whole blood / packed RBC storage limit
# (widely documented transfusion-medicine standard). Does NOT apply as-is to
# platelets (5 days) or fresh frozen plasma (up to 1 year frozen) - this
# prototype models whole-blood/RBC units only.

UNIT_VOLUME_ML = 450
# Standard single whole-blood donation volume (config constant, not derived).

QUALITY_HOLD_RATE = 0.015
# Heuristic placeholder for non-expiry discards (e.g. failed screening,
# hemolysis, bag defect) - NOT a clinical rule, just a small constant to
# avoid pretending 100% of real-world discards are expiry-driven. Real
# inventory_data.csv shows ~5.4% discard-of-received nationally; expiry
# alone in this simulation already produces part of that, this adds a
# residual random-failure component. Calibrate against real lab QC logs
# before production use.

PRIORITY_WEIGHTS = {"Routine": 0.70, "Urgent": 0.22, "Emergency": 0.08}
# Heuristic placeholder distribution only, NOT derived from any clinical
# triage protocol. A real system must classify priority from actual clinical
# indication (trauma, scheduled surgery, obstetric emergency, etc.), not a
# random draw. This exists purely so blood_requests.csv has a priority field
# to demonstrate priority-ranked allocation logic.

REQUEST_SIZE_CHOICES = [1, 1, 1, 2, 2, 3, 4]
# Heuristic distribution of units-per-request (skewed toward 1-2 units,
# occasional larger multi-unit requests e.g. surgery). Not clinically derived.

ABO_GROUPS = ["A", "B", "AB", "O"]
RH_VALUES = ["+", "-"]

# ----------------------------------------------------------------------------
rng = np.random.default_rng(SEED)


def sub_rng(label: str) -> np.random.Generator:
    """Deterministic, independent sub-stream keyed by label (for reproducibility
    even if generation order of different sections changes). Uses hashlib
    (stable across processes/runs) instead of Python's built-in hash(), which
    is randomized per-process by default (PYTHONHASHSEED) and is NOT safe for
    reproducible seeding."""
    import hashlib
    label_seed = int(hashlib.sha256(label.encode()).hexdigest(), 16) % (2**31)
    return np.random.default_rng([SEED, label_seed])


# ----------------------------------------------------------------------------
# STEP 1 — Load REAL source data (read-only, never mutated)
# ----------------------------------------------------------------------------
donors_raw = pd.read_csv(DONOR_SOURCE_DIR / "donors.csv")
history_raw = pd.read_csv(DONOR_SOURCE_DIR / "donation_history.csv")
supply = pd.read_csv(REAL / "supply_data.csv", parse_dates=["date"])
demand = pd.read_csv(REAL / "demand_data.csv", parse_dates=["date"])

history_raw["donation_date"] = pd.to_datetime(history_raw["donation_date"])
donors_raw["last_donation_date"] = pd.to_datetime(donors_raw["last_donation_date"])

print(f"Loaded donors_raw: {len(donors_raw)} rows")
print(f"Loaded history_raw: {len(history_raw)} rows")
print(f"Loaded supply: {len(supply)} rows, demand: {len(demand)} rows")

# ----------------------------------------------------------------------------
# STEP 2 — Enrich donors.csv: assign Rh factor deterministically per donor
# ----------------------------------------------------------------------------
r1 = sub_rng("rh_assignment")
donors = donors_raw.copy().sort_values("donor_id").reset_index(drop=True)
rh_draw = r1.random(len(donors))
donors["rh_factor"] = np.where(rh_draw < RH_POSITIVE_PROB, "+", "-")
donors["abo_rh"] = donors["blood_group"] + donors["rh_factor"]

print("\nDonor Rh assignment check:")
print(donors["rh_factor"].value_counts(normalize=True))
print(donors["abo_rh"].value_counts())

donors_out_cols = [
    "donor_id", "name", "blood_group", "rh_factor", "abo_rh", "phone",
    "last_donation_date", "donation_count", "contact_opt_in",
]
donors_final = donors[donors_out_cols].copy()
donors_final["last_donation_date"] = donors_final["last_donation_date"].dt.strftime("%Y-%m-%d")

# donation_history.csv: copy through UNCHANGED (already 100% internally
# consistent with donors.csv - verified in analysis phase). We keep it
# normalized (blood group is looked up via donor_id, not duplicated here).
history_final = history_raw.copy()
history_final["donation_date"] = history_final["donation_date"].dt.strftime("%Y-%m-%d")

# ----------------------------------------------------------------------------
# STEP 3 — blood_units.csv: explode every REAL donation into 1+ real units
# ----------------------------------------------------------------------------
donor_lookup = donors.set_index("donor_id")[["blood_group", "rh_factor", "abo_rh"]]

hist = history_raw.merge(donor_lookup, left_on="donor_id", right_index=True, how="left")
assert hist["blood_group"].isna().sum() == 0, "orphan donor_id in donation_history"

unit_rows = []
uid_counter = 1
for row in hist.itertuples(index=False):
    for _ in range(int(row.units_donated)):
        unit_rows.append({
            "unit_id": f"BU{uid_counter:07d}",
            "donation_id": row.donation_id,
            "donor_id": row.donor_id,
            "abo_group": row.blood_group,
            "rh_factor": row.rh_factor,
            "blood_group": row.abo_rh,
            "collection_date": row.donation_date,
            "volume_ml": UNIT_VOLUME_ML,
        })
        uid_counter += 1

blood_units = pd.DataFrame(unit_rows)
blood_units["collection_date"] = pd.to_datetime(blood_units["collection_date"])
blood_units["expiry_date"] = blood_units["collection_date"] + pd.Timedelta(days=SHELF_LIFE_DAYS)

print(f"\nblood_units generated: {len(blood_units)} "
      f"(from {len(hist)} donation events, {hist['units_donated'].sum()} declared units)")
assert len(blood_units) == hist["units_donated"].sum(), "unit explosion count mismatch"

# ----------------------------------------------------------------------------
# STEP 4 — blood_requests.csv: branch-scale demand, shaped by REAL national
#           demand pattern, sized off this branch's REAL supply
# ----------------------------------------------------------------------------
# 4a. Real national utilization ratio per ABO group (demand/supply), used to
#     preserve which groups are structurally tighter at national level.
national_supply_total = supply.groupby("blood_group")["units_collected"].sum()
national_demand_total = demand.groupby("blood_group")["units_demanded"].sum()
national_util_ratio = (national_demand_total / national_supply_total).to_dict()
print("\nNational demand/supply utilization ratio by ABO group (real data):")
print(national_util_ratio)

# 4b. This branch's real total supply per ABO group (from blood_units, which
#     came straight out of donation_history.csv)
branch_supply_total = blood_units.groupby("abo_group").size().to_dict()

# 4c. Target total branch demand per ABO group = branch supply * national ratio
branch_demand_target = {g: branch_supply_total.get(g, 0) * national_util_ratio.get(g, 1.0)
                         for g in ABO_GROUPS}
print("\nBranch supply totals (real, from donation_history):", branch_supply_total)
print("Branch demand targets (derived):", {k: round(v, 1) for k, v in branch_demand_target.items()})

# 4d. Daily shape weights from REAL demand_data.csv, restricted to the same
#     date range covered by this branch's donation_history (so seasonality/
#     trend context matches), normalized to sum to 1 per group.
date_min, date_max = history_raw["donation_date"].min(), history_raw["donation_date"].max()
demand_window = demand[(demand["date"] >= date_min) & (demand["date"] <= date_max)].copy()
demand_window["weight"] = demand_window.groupby("blood_group")["units_demanded"].transform(lambda s: s / s.sum())

# 4e. Distribute each group's branch demand target across days using the real
#     shape weights, then round while preserving the exact integer total
#     (largest-remainder method) so the branch total is respected exactly per
#     group and only rounding noise (not model error) affects daily figures.
def largest_remainder_round(values: pd.Series, total_target: float) -> np.ndarray:
    raw = values * total_target
    floor_vals = np.floor(raw).astype(int).to_numpy().copy()
    remainder_total = int(round(total_target)) - floor_vals.sum()
    if remainder_total > 0:
        remainders = (raw - floor_vals).to_numpy()
        top_idx = np.argsort(-remainders)[:remainder_total]
        floor_vals[top_idx] += 1
    return floor_vals

daily_group_frames = []
for g in ABO_GROUPS:
    sub = demand_window[demand_window["blood_group"] == g].copy()
    target = branch_demand_target[g]
    sub["units_target"] = largest_remainder_round(sub["weight"], target)
    daily_group_frames.append(sub[["date", "blood_group", "units_target"]])

branch_daily_demand = pd.concat(daily_group_frames, ignore_index=True)
branch_daily_demand = branch_daily_demand[branch_daily_demand["units_target"] > 0].reset_index(drop=True)

print(f"\nDaily branch demand rows (group-days with >0 target): {len(branch_daily_demand)}")
print("Reconciliation check (target vs generated total):")
check = branch_daily_demand.groupby("blood_group")["units_target"].sum()
for g in ABO_GROUPS:
    print(f"  {g}: target={branch_demand_target[g]:.1f}  generated={check.get(g, 0)}")

# 4f. Split each day's ABO total into individual requests, assign Rh via the
#     same population distribution used for donors (documented assumption),
#     assign a heuristic priority label, generate request_id.
r_size = sub_rng("request_sizing")
r_rh = sub_rng("request_rh")
r_prio = sub_rng("request_priority")

request_rows = []
rid_counter = 1
priorities = list(PRIORITY_WEIGHTS.keys())
priority_p = list(PRIORITY_WEIGHTS.values())

for row in branch_daily_demand.itertuples(index=False):
    remaining = int(row.units_target)
    while remaining > 0:
        size = int(r_size.choice(REQUEST_SIZE_CHOICES))
        size = min(size, remaining)
        rh = "+" if r_rh.random() < RH_POSITIVE_PROB else "-"
        priority = r_prio.choice(priorities, p=priority_p)
        request_rows.append({
            "request_id": f"BR{rid_counter:07d}",
            "request_date": row.date,
            "abo_group": row.blood_group,
            "rh_factor": rh,
            "blood_group": row.blood_group + rh,
            "units_requested": size,
            "priority": priority,
        })
        rid_counter += 1
        remaining -= size

blood_requests = pd.DataFrame(request_rows)
blood_requests["request_date"] = pd.to_datetime(blood_requests["request_date"])
print(f"\nblood_requests generated: {len(blood_requests)} individual requests, "
      f"{blood_requests['units_requested'].sum()} total units requested")

# ----------------------------------------------------------------------------
# STEP 5 — compatibility_rules.csv: standard ABO/Rh RBC compatibility
# ----------------------------------------------------------------------------
def abo_compatible(donor_abo: str, recipient_abo: str) -> bool:
    # Recipient can receive donor RBCs if recipient has no antibodies against
    # donor antigens. O = universal donor, AB = universal recipient.
    rules = {
        "O": {"O", "A", "B", "AB"},   # O can donate to anyone
        "A": {"A", "AB"},
        "B": {"B", "AB"},
        "AB": {"AB"},
    }
    return recipient_abo in rules[donor_abo]


def rh_compatible(donor_rh: str, recipient_rh: str) -> bool:
    if donor_rh == "-":
        return True  # Rh- donor compatible with Rh- and Rh+ recipients
    return recipient_rh == "+"  # Rh+ donor only compatible with Rh+ recipient


compat_rows = []
for d_abo in ABO_GROUPS:
    for d_rh in RH_VALUES:
        for r_abo in ABO_GROUPS:
            for r_rh in RH_VALUES:
                compatible = abo_compatible(d_abo, r_abo) and rh_compatible(d_rh, r_rh)
                compat_rows.append({
                    "donor_group": d_abo + d_rh,
                    "recipient_group": r_abo + r_rh,
                    "compatible": "Yes" if compatible else "No",
                    "rule_type": "Whole blood / packed RBC transfusion",
                    "source_note": ("Standard ABO/Rh(D) RBC compatibility "
                                     "(Landsteiner's law + Rh rule). Does NOT "
                                     "cover plasma or platelet compatibility "
                                     "(plasma follows reverse-ABO logic). "
                                     "Requires sign-off by a licensed blood "
                                     "bank professional before clinical use."),
                })

compatibility_rules = pd.DataFrame(compat_rows)
print(f"\ncompatibility_rules generated: {len(compatibility_rules)} rows "
      f"({compatibility_rules['compatible'].eq('Yes').sum()} compatible pairs)")

# ----------------------------------------------------------------------------
# STEP 6 — Simulate FEFO issuance -> blood_issues.csv, update unit/request status
# ----------------------------------------------------------------------------
compat_lookup = {}
for row in compatibility_rules.itertuples(index=False):
    compat_lookup.setdefault(row.recipient_group, [])
    if row.compatible == "Yes":
        compat_lookup[row.recipient_group].append(row.donor_group)

blood_units = blood_units.sort_values(["blood_group", "expiry_date", "collection_date"]).reset_index(drop=True)
blood_units["status"] = "Available"
blood_units["discard_reason"] = None
blood_units["issue_id"] = None

r_quality = sub_rng("quality_hold")
quality_draw = r_quality.random(len(blood_units))
quality_fail_mask = quality_draw < QUALITY_HOLD_RATE
blood_units.loc[quality_fail_mask, "status"] = "Discarded"
blood_units.loc[quality_fail_mask, "discard_reason"] = "Quality Hold (heuristic, non-clinical placeholder)"

# available-unit pools per blood_group, kept sorted by expiry (FEFO), as
# collections.deque of indices for O(1) popleft. Sorted ascending by
# expiry_date (~= collection_date ascending), so within a pool: any unit
# whose expiry has passed can only ever be at/near the front, and any unit
# not yet collected can only ever be at/near the back-of-remaining-front-run.
from collections import deque

avail_mask = blood_units["status"] == "Available"
pools = {}
for bg, idx in blood_units[avail_mask].groupby("blood_group").groups.items():
    pools[bg] = deque(idx)  # already sorted by expiry_date, collection_date

# Precompute plain-python lookup arrays (avoid repeated pandas .loc/.at cost
# inside a tight loop over tens of thousands of requests/units)
expiry_map = blood_units["expiry_date"].to_dict()
collection_map = blood_units["collection_date"].to_dict()
unit_id_map = blood_units["unit_id"].to_dict()

blood_requests = blood_requests.sort_values(
    by=["request_date", "priority"],
    key=lambda col: col.map({"Emergency": 0, "Urgent": 1, "Routine": 2}) if col.name == "priority" else col,
).reset_index(drop=True)
blood_requests["status"] = "Unfulfilled"
blood_requests["units_fulfilled"] = 0

issue_rows = []
unit_updates = {}  # uidx -> (status, issue_id)
iid_counter = 1
CURRENT_DATE = pd.Timestamp(supply["date"].max())  # 2026-09-04, "today" in the real data

req_ids = blood_requests["request_id"].to_numpy()
req_dates = blood_requests["request_date"].to_numpy()
req_groups = blood_requests["blood_group"].to_numpy()
req_units_needed = blood_requests["units_requested"].to_numpy()
fulfilled_arr = np.zeros(len(blood_requests), dtype=int)

for ridx in range(len(blood_requests)):
    needed = int(req_units_needed[ridx])
    fulfilled = 0
    req_date = req_dates[ridx]
    own_group = req_groups[ridx]
    # Match own exact blood group FIRST (standard blood-bank practice - never
    # spend a compatible-but-non-identical unit, e.g. O-, when an exact match
    # is available). Only fall back to other compatible groups if the exact
    # group can't fully cover the request. Earlier version of this script
    # iterated compat_lookup's raw generation order (A,B,AB,O), which meant
    # universal recipients like AB+ almost always got matched from the large
    # A+ pool before AB+ was ever tried - AB units piled up unused and
    # expired at a 90%+ rate. Fixed by forcing exact-match-first ordering.
    compatible_others = [g for g in compat_lookup.get(own_group, []) if g != own_group]
    candidate_groups = [own_group] + compatible_others

    for donor_group in candidate_groups:
        if needed <= 0:
            break
        pool = pools.get(donor_group)
        if not pool:
            continue
        # Drop permanently-expired units from the front (they can never be
        # used by this or any later request, since dates only increase).
        while pool and expiry_map[pool[0]] < req_date:
            pool.popleft()
        # Issue from the front while eligible (collected on/before req_date).
        while pool and needed > 0 and collection_map[pool[0]] <= req_date:
            uidx = pool.popleft()
            unit_updates[uidx] = ("Issued", f"BI{iid_counter:07d}")
            issue_rows.append({
                "issue_id": f"BI{iid_counter:07d}",
                "request_id": req_ids[ridx],
                "unit_id": unit_id_map[uidx],
                "issue_date": req_date,
                "exact_match": "Yes" if donor_group == req_groups[ridx] else "No",
            })
            iid_counter += 1
            needed -= 1
            fulfilled += 1
        # if pool[0] is not yet collected as of req_date, remaining units in
        # this donor_group pool are all even later (sorted ascending) -> stop

    fulfilled_arr[ridx] = fulfilled

blood_requests["units_fulfilled"] = fulfilled_arr
blood_requests["status"] = np.select(
    [fulfilled_arr == 0, fulfilled_arr < req_units_needed],
    ["Unfulfilled", "Partial"],
    default="Fulfilled",
)

blood_issues = pd.DataFrame(issue_rows)

# Apply all unit status updates in one vectorized pass
if unit_updates:
    upd_idx = list(unit_updates.keys())
    upd_status = [v[0] for v in unit_updates.values()]
    upd_issue_id = [v[1] for v in unit_updates.values()]
    blood_units.loc[upd_idx, "status"] = upd_status
    blood_units.loc[upd_idx, "issue_id"] = upd_issue_id
print(f"\nblood_issues generated: {len(blood_issues)}")
print("\nRequest fulfillment status distribution:")
print(blood_requests["status"].value_counts())

# Mark remaining Available units that are past shelf life (as of CURRENT_DATE) as Expired
still_available = blood_units["status"] == "Available"
past_expiry = blood_units["expiry_date"] < CURRENT_DATE
expire_mask = still_available & past_expiry
blood_units.loc[expire_mask, "status"] = "Expired"
blood_units.loc[expire_mask, "discard_reason"] = "Expired (shelf life exceeded)"

print("\nFinal blood_units status distribution:")
print(blood_units["status"].value_counts())

# ----------------------------------------------------------------------------
# STEP 7 — Write outputs
# ----------------------------------------------------------------------------
donors_final.to_csv(OUT_SYN / "donors.csv", index=False)
history_final.to_csv(OUT_SYN / "donation_history.csv", index=False)

bu_out = blood_units.copy()
bu_out["collection_date"] = bu_out["collection_date"].dt.strftime("%Y-%m-%d")
bu_out["expiry_date"] = bu_out["expiry_date"].dt.strftime("%Y-%m-%d")
bu_out = bu_out[["unit_id", "donation_id", "donor_id", "abo_group", "rh_factor",
                  "blood_group", "collection_date", "expiry_date", "volume_ml",
                  "status", "discard_reason", "issue_id"]]
bu_out.to_csv(OUT_SYN / "blood_units.csv", index=False)

br_out = blood_requests.copy()
br_out["request_date"] = br_out["request_date"].dt.strftime("%Y-%m-%d")
br_out = br_out[["request_id", "request_date", "abo_group", "rh_factor", "blood_group",
                  "units_requested", "priority", "status", "units_fulfilled"]]
br_out.to_csv(OUT_SYN / "blood_requests.csv", index=False)

bi_out = blood_issues.copy()
if len(bi_out) > 0:
    bi_out["issue_date"] = pd.to_datetime(bi_out["issue_date"]).dt.strftime("%Y-%m-%d")
bi_out.to_csv(OUT_SYN / "blood_issues.csv", index=False)

compatibility_rules.to_csv(OUT_RULES / "compatibility_rules.csv", index=False)

print("\n✅ All files written to", OUT_SYN, "and", OUT_RULES)
